name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # 告訴 Node 去子資料夾找 package-lock.json
          cache-dependency-path: counselor/package-lock.json

      - name: Install and Build
        # 關鍵：設定 working-directory，讓指令在 counselor 資料夾執行
        working-directory: counselor
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'counselor/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2